flask/app/models.py
from app import db
from datetime import datetime
import re


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(140))
    slug = db.Column(db.String(140))

    def __init__(self,*args,**kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<Tag id: {}, title: {}>'.format(self.id, self.name)

flask/app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy     # ORM (object relation model) system
from flask_migrate import Migrate
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)
db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', Migrate)

flask/app/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post


posts = Blueprint('posts', __name__, template_folder='posts/templates')
print(f"@@@@@@@@@@@@@@@@ {__name__}")

@posts.route('/')
def index():
    posts = Post.query.all()
    return render_template('posts/index.html', posts=posts)

@posts.route('/<slug>')
def post_detail(slug):
    posts = Post.query.filter(Post.slug==slug).first()
    return render_template('posts/post_detail.html', post=posts)

flask/app/main.py
from app import app
from app import db
from blueprint import posts
import view




app.register_blueprint(posts, url_prefix='/blog')
print(f"1 @@@@@@@@@@@@ {posts}")
if __name__ == "__main__":
    app.run()

flask/app/templates/base.html
<!DOCTYPE html>

<html lang="en">

  <head>
      <meta charset="UTF-8">
      <title>
        {% block title %}

        {% endblock %} | Flask app
      </title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index') }}">VPA Lib</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('posts.index') }}">Article 1</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#2">Article 2</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#3">Article 3</a>
            </li>
          </ul>

          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>

        </div>
      </div>
    </nav>


    <div class="container">
      <div class="row">
        <h1>
          {% block content_title %}
          {% endblock %}
        </h1>
          {% block content %}
          {% endblock %}
      </div>
    </div>

  </body>

</html>

flask/app/templates/index.html
{% extends 'base.html' %}

{% block title %}
  LIBRARY VPA
{% endblock %}

{% block content_title %}
WinCC OA
{% endblock %}

{% block content %}
  <h5>Content:</h5>
  <p>
    1. install and activation on Codemeter</br>
    2. Create proect and basic views</br>
    3. Create panel of conveyor</br>
    4. Create datapoint winCC OA & Imports tags from TIA Portal*</br>
    5. Create context window for conveyor*</br>
    6. Write scripts for animation conveyor*</br>
    7. Connect to PLC simulator**</br>
  </p>
{% endblock %}